-- Jeu de données annotées de départ (positive=1/negative=0 exclusifs, ou les deux à 0 pour neutre)
INSERT INTO tweets (text, positive, negative) VALUES
('I absolutely love this new phone, best purchase ever!', 1, 0),
('This is the worst service I have ever experienced.', 0, 1),
('Had a great time at the concert last night!', 1, 0),
('I am so disappointed with this product, total waste of money.', 0, 1),
('The customer support team was incredibly helpful and kind.', 1, 0),
('This app keeps crashing, it is so frustrating.', 0, 1),
('What a beautiful sunny day, feeling amazing!', 1, 0),
('I cannot believe how rude the staff was to me.', 0, 1),
('Just got promoted at work, so happy right now!', 1, 0),
('My flight got cancelled and no one is helping me.', 0, 1),
('This restaurant has the best food I have ever tasted.', 1, 0),
('The delivery was late again, this is unacceptable.', 0, 1),
('I am grateful for all the support from my friends.', 1, 0),
('This laptop broke after just two days of use.', 0, 1),
('Excited to start my new job tomorrow!', 1, 0),
('I regret buying this, it does not work at all.', 0, 1),
('The movie was fantastic, I really enjoyed it.', 1, 0),
('Terrible experience, I want a refund immediately.', 0, 1),
('Thank you so much, you made my day better!', 1, 0),
('I am furious about the way this was handled.', 0, 1),
('Amazing customer service, they solved my issue in minutes.', 1, 0),
('This is so annoying, nothing works as expected.', 0, 1),
('Feeling blessed and thankful for everything today.', 1, 0),
('I am extremely unhappy with the quality of this item.', 0, 1),
('Best vacation ever, I do not want to leave!', 1, 0),
('The app update ruined everything, please fix it.', 0, 1),
('So proud of my team for winning the championship!', 1, 0),
('I have been waiting for hours and no one responds.', 0, 1),
('This book changed my life, highly recommend it.', 1, 0),
('Absolutely horrible, I will never buy this again.', 0, 1),
('Great job everyone, this project turned out amazing!', 1, 0),
('I am so tired of these constant delays.', 0, 1),
('The weather is perfect for a walk in the park.', 1, 0),
('This is a scam, do not trust this company.', 0, 1),
('I love how easy this software is to use.', 1, 0),
('Nothing but problems since I started using this.', 0, 1),
('My family surprised me with a wonderful party.', 1, 0),
('The hotel room was dirty and smelled awful.', 0, 1),
('Congratulations on your success, well deserved!', 1, 0),
('I am disgusted by how this situation was managed.', 0, 1),
('This coffee shop has the best atmosphere ever.', 1, 0),
('The product arrived broken and damaged.', 0, 1),
('I appreciate your quick response, thank you!', 1, 0),
('Such a waste of time, do not recommend at all.', 0, 1),
('Feeling motivated and ready to take on the day!', 1, 0),
('This update broke all my saved settings.', 0, 1),
('The staff went above and beyond to help me.', 1, 0),
('I am so upset about the price increase.', 0, 1),
('What an incredible performance by the whole cast.', 1, 0),
('This is ridiculous, I want to speak to a manager.', 0, 1),
('I had a wonderful weekend with my family.', 1, 0),
('The internet connection keeps dropping constantly.', 0, 1),
('Loving the new design, it looks so much better.', 1, 0),
('I am tired of dealing with this broken system.', 0, 1),
('This place has amazing energy and great music.', 1, 0),
('Never ordering from here again, awful experience.', 0, 1),
('So thankful for my supportive colleagues today.', 1, 0),
('The refund process is taking way too long.', 0, 1),
('I am impressed by how fast this was delivered.', 1, 0),
('This is by far the worst app I have used.', 0, 1),
('Weather looks fine today, nothing special.', 0, 0),
('I went to the store to buy some groceries.', 0, 0),
('The meeting is scheduled for 3pm tomorrow.', 0, 0),
('He walked to the office as usual this morning.', 0, 0),
('The report will be published next week.', 0, 0),
('She is reading a book about history.', 0, 0),
('The train arrives at the station every hour.', 0, 0),
('This document contains the quarterly numbers.', 0, 0);
